export const PALETTE = {
  cream: '#F7F3EE',
  creamDark: '#EDE7DE',
  sageLight: '#D4DFCF',
  sage: '#A8B5A2',
  sageDark: '#6E7D68',
  roseLight: '#E8D5D0',
  rose: '#C9A9A6',
  roseDark: '#9E7570',
  charcoal: '#3D3D3D',
  charcoalLight: '#6B6B6B',
  muted: '#B0B0B0',
}

export const TODO_COLORS = [
  { name: 'Salbei',       hex: '#A8B5A2' },
  { name: 'Altrosa',      hex: '#C9A9A6' },
  { name: 'Lavendel',     hex: '#B8B0CC' },
  { name: 'Himmelblau',   hex: '#A8C4D4' },
  { name: 'Pfirsich',     hex: '#E8C4A0' },
  { name: 'Goldgelb',     hex: '#D4B87A' },
  { name: 'Terrakotta',   hex: '#C4856A' },
  { name: 'Waldgrün',     hex: '#7A9E7E' },
  { name: 'Schieferblau', hex: '#8A9BAE' },
  { name: 'Pflaume',      hex: '#9E7E9E' },
  { name: 'Leinen',       hex: '#D4C8B8' },
  { name: 'Anthrazit',    hex: '#6B6B6B' },
  { name: 'Bordeaux',     hex: '#8b1a4a' },
  { name: 'Koralle',      hex: '#E07060' },
  { name: 'Mint',         hex: '#7EC8B0' },
  { name: 'Indigo',       hex: '#6B7EC8' },
  { name: 'Senf',         hex: '#C8A83A' },
  { name: 'Ozean',        hex: '#4A90B8' },
  { name: 'Flieder',      hex: '#C8A0D4' },
  { name: 'Smaragd',      hex: '#4A9E7A' },
  { name: 'Zimt',         hex: '#C87840' },
  { name: 'Hellgrau',     hex: '#B0B0B8' },
  { name: 'Rosa',         hex: '#F0A0B8' },
  { name: 'Teal',         hex: '#5AB8B0' },
]

export const DEFAULT_TODO_COLOR = TODO_COLORS[0].hex
